version: "3.7"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=test

  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
